spring:
  #  security:
  #    user:
  #      name: admin
  #      password: 12345678
  #  autoconfigure:
  #    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration

  datasource:
    default-catalog: spring-library
    jndi-name: jdbc/SpringLibrary
    url: jdbc:mysql://localhost:3306/spring-library
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
    show-sql: true

logging:
  file:
    name: /Users/leokooper/git/spring-projects/spring-library/src/main/resources/library.log
  pattern:
    file: "d{HH:mm:ss} %-5p [%c] - %m%n"
  level:
    ROOT: error
    org.springframework: warn
    javax.faces: warn
    org.omnifaces: warn
    org.springframework.security: warn
    org.hibernate: warn
    org.hibernate.type.descriptor.sql: warn
